### ISSUE TITLE
/oauth/authorize redirects to /oauth/errors (argument of type 'NoneType' is not iterable)

### ISSUE THREAD

**Issue by kpcyrd** [authlib/example-oauth2-server#29]
I cloned the repo, installed the dependencies and followed step 1-5 in the readme. When opening 127.0.0.1:8000 I get directed to `/oauth/authorize` on port 5000. To this point, everything works as expected, but instead of the authorize page I get redirected to `/oauth/errors` with error `argument of type 'NoneType' is not iterable`

app.py (127.0.0.1:5000)

```
127.0.0.1 - - [26/Oct/2016 02:21:49] "GET /oauth/authorize?response_type=code&client_id=gjIsasqZPgxLbqkZ4xGMTQmfVnAzvG6EhjJoB92A&redirect_uri=http%3A%2F%2F127.0.0.1%3A8000%2Fauthorized&scope=email HTTP/1.1" 302 -
127.0.0.1 - - [26/Oct/2016 02:21:50] "GET /oauth/errors?error=argument+of+type+%27NoneType%27+is+not+iterable HTTP/1.1" 404 -
```

I'm assuming this could be related to idan/oauthlib#436 but that's just a wild guess.

**Comment by kpcyrd** [comment]
I modified the exception handler that was swallowing the exception and added a `raise` (`flask_oauthlib/provider/oauth2.py:400`), according to the stacktrace the exception is initially raised by checking for `'openid'` in `request.scopes`, which should be a list, but is `None`.

```
Traceback (most recent call last):
  File "/home/user/example-oauth2-server/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/user/example-oauth2-server/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/user/example-oauth2-server/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/example-oauth2-server/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/user/example-oauth2-server/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/example-oauth2-server/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/example-oauth2-server/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/example-oauth2-server/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/user/example-oauth2-server/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/example-oauth2-server/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/example-oauth2-server/lib/python3.4/site-packages/flask_oauthlib/provider/oauth2.py", line 400, in decorated
    raise e
  File "/home/user/example-oauth2-server/lib/python3.4/site-packages/flask_oauthlib/provider/oauth2.py", line 387, in decorated
    uri, http_method, body, headers
  File "/home/user/example-oauth2-server/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "/home/user/example-oauth2-server/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/endpoints/authorization.py", line 113, in validate_authorization_request
    return response_type_handler.validate_authorization_request(request)
  File "/home/user/example-oauth2-server/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/grant_types/openid_connect.py", line 77, in validate_authorization_request
    return self._handler_for_request(request).validate_authorization_request(request)
  File "/home/user/example-oauth2-server/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/grant_types/openid_connect.py", line 67, in _handler_for_request
    if "openid" in request.scopes:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by weichanxiang** [comment]
I have been experiencing the exact same issue. Are there any fixes or workarounds to this error?

**Comment by kpcyrd** [comment]
@weichanxiang can you please share how you fixed the issue? I worked around it in a test by editing the python files of the library, but that doesn't work unless I commit my modified library with my code.

**Comment by weichanxiang** [comment]
@kpcyrd I had to manually edit the python library locally as it seems to be an inconsistency in the library itself. This works for my application. However, there is a fork that was mentioned at Sumukh/oauthlib that you can perhaps try if you need to download it remotely?

**Comment by WillCallahan** [comment]
I have the exact same issue.

**Comment by Sumukh** [comment]
I list `https://github.com/Sumukh/oauthlib/archive/master.zip` in my requirements.txt file - that should work for now.

**Comment by togapaulo** [comment]
http://127.0.0.1:5000/oauth/errors?error=argument+of+type+%27NoneType%27+is+not+iterable ??

**Comment by lepture** [comment]
the example is updated to [Authlib](https://authlib.org/)
