### ISSUE TITLE
Set-up instructions no longer work

### ISSUE THREAD

**Issue by ignasGaubas** [authlib/example-oauth2-server#44]
If you follow set up instruncions and download project. Create conda env. Install flask, flask-sqlalchemy and Authlib in that env. Then try to run app.py from pycharm, you get error.
I still had conda env, which was created in September and with which prject used to run, and with that env it still runs, but if I create new env following your instructions, I get error:
`C:\Users\Ignas\Anaconda3\envs\ugpsts\python.exe -m flask run
Traceback (most recent call last):
  File "C:\Users\Ignas\Anaconda3\envs\ugpsts\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Ignas\Anaconda3\envs\ugpsts\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\Ignas\Anaconda3\envs\ugpsts\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Ignas\Anaconda3\envs\ugpsts\lib\site-packages\flask\__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "C:\Users\Ignas\Anaconda3\envs\ugpsts\lib\site-packages\flask\app.py", line 25, in <module>
    from . import cli, json
  File "C:\Users\Ignas\Anaconda3\envs\ugpsts\lib\site-packages\flask\cli.py", line 18, in <module>
    import ssl
  File "C:\Users\Ignas\Anaconda3\envs\ugpsts\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed: The specified module could not be found.
`

**Comment by ignasGaubas** [comment]
These are my "conda list"'s from older and new env. There are different package names, as well as new env has 3 packages more, namely ca-certificates, openssl, sqlite.
[ugpsts.txt](https://github.com/authlib/example-oauth2-server/files/2704594/ugpsts.txt)
[apilab.txt](https://github.com/authlib/example-oauth2-server/files/2704595/apilab.txt)

**Comment by lepture** [comment]
The error shows nothing about this project.
