### ISSUE TITLE
authlib module not found error

### ISSUE THREAD

**Issue by raveenb** [authlib/example-oauth2-server#62]
I am getting a module not found error for authlib, i had followed the instructions as written

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/Users/raveenbeemsingh/Developer/projects/flask_oauth/example-oauth2-server/app.py", line 1, in <module>
    from website.app import create_app
  File "/Users/raveenbeemsingh/Developer/projects/flask_oauth/example-oauth2-server/website/app.py", line 3, in <module>
    from .models import db
  File "/Users/raveenbeemsingh/Developer/projects/flask_oauth/example-oauth2-server/website/models.py", line 3, in <module>
    from authlib.integrations.sqla_oauth2 import (
ModuleNotFoundError: No module named 'authlib'
```

**Comment by raveenb** [comment]
this is my directory structure

```
  ~/Developer/…/flask_oauth/example-oauth2-server    venv 
   ls
README.md        __pycache__      app.py           db.sqlite        requirements.txt venv             website
```

**Comment by lepture** [comment]
try to install:

```
$ pip install -r requirements.txt
```

find out if it is not installed successful with:

```
$ pip freeze
```
