### ISSUE TITLE
ValueError: 'name' may not contain a dot '.' character. when execute flask run

### ISSUE THREAD

**Issue by janaka1984** [authlib/example-oauth2-server#80]
$ flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "c:\users\janaka_w\appdata\local\programs\python\python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\janaka_w\appdata\local\programs\python\python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\PYTHON TEST PROJECT\example-oauth2-server-master\env-auth\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "e:\python test project\example-oauth2-server-master\env-auth\lib\site-packages\flask\cli.py", line 990, in main
    cli.main(args=sys.argv[1:])
  File "e:\python test project\example-oauth2-server-master\env-auth\lib\site-packages\flask\cli.py", line 596, in main
    return super().main(*args, **kwargs)
  File "e:\python test project\example-oauth2-server-master\env-auth\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "e:\python test project\example-oauth2-server-master\env-auth\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "e:\python test project\example-oauth2-server-master\env-auth\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "e:\python test project\example-oauth2-server-master\env-auth\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "e:\python test project\example-oauth2-server-master\env-auth\lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "e:\python test project\example-oauth2-server-master\env-auth\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "e:\python test project\example-oauth2-server-master\env-auth\lib\site-packages\flask\cli.py", line 845, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "e:\python test project\example-oauth2-server-master\env-auth\lib\site-packages\flask\cli.py", line 321, in __init__
    self._load_unlocked()
  File "e:\python test project\example-oauth2-server-master\env-auth\lib\site-packages\flask\cli.py", line 346, in _load_unlocked
    self._app = rv = self.loader()
  File "e:\python test project\example-oauth2-server-master\env-auth\lib\site-packages\flask\cli.py", line 406, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "e:\python test project\example-oauth2-server-master\env-auth\lib\site-packages\flask\cli.py", line 256, in locate_app
    __import__(module_name)
  File "E:\PYTHON TEST PROJECT\example-oauth2-server-master\app.py", line 1, in <module>
    from website.app import create_app
  File "E:\PYTHON TEST PROJECT\example-oauth2-server-master\website\app.py", line 5, in <module>
    from .routes import bp
  File "E:\PYTHON TEST PROJECT\example-oauth2-server-master\website\routes.py", line 11, in <module>
    bp = Blueprint(__name__, 'home')
  File "e:\python test project\example-oauth2-server-master\env-auth\lib\site-packages\flask\blueprints.py", line 195, in __init__
    raise ValueError("'name' may not contain a dot '.' character.")
ValueError: 'name' may not contain a dot '.' character.

**Comment by yangjinghit** [comment]
i got the same issue, have you solved it ? @janaka1984

**Comment by yangjinghit** [comment]
Flask==1.1.2
Flask-SQLAlchemy==2.5.1
Authlib==0.14.3
this version is ok

**Comment by TechStudent11** [comment]
I think the issue is in `websites/routes.py`. Change this line:
```python
bp = Blueprint(__name__, 'home')
```
to this line:
```python
bp = Blueprint('home', __name__)
```
and it should work.

**Comment by lepture** [comment]
updated the demo. Thanks @TechStudent11

**Comment by TechStudent11** [comment]
@lepture no prob :)

**Comment by bera-bin-le** [comment]
@lepture the main branch README still has the wrong example code (the Hello World section).
